modLoader="javafml"
loaderVersion="[28,)"

issueTrackerURL="https://github.com/superfluke/WorleyCaves/issues"

[[mods]]
	modId="worleycaves"
	version="1.14.4-1.6.0"
	displayName="Worley's Caves"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/worleys-caves"
	credits=""
	authors="SuperFluke and booleanbyte"
	description='''
	Cave generation with Worley noise
	'''

[[dependencies.worleycaves]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
    
[[dependencies.worleycaves]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"